name: CI

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read
    deployments: write
    pull-requests: write

jobs:
    ESLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare
              uses: ./.github/actions/prepare

            - name: Install dependencies
              run: pnpm install

            - name: Run ESLint
              run: pnpm lint

    Prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare
              uses: ./.github/actions/prepare

            - name: Install dependencies
              run: pnpm install

            - name: Run Prettier
              run: pnpm format

    Preview:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        needs:
            - Build
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare
              uses: ./.github/actions/prepare

            - name: Install dependencies
              run: pnpm install

            - name: Create .env
              run: |
                  touch .env
                  echo "VITE_TEXT_ALIVE_APP_API_TOKEN=${{ secrets.TEXT_ALIVE_APP_API_TOKEN }}" >> .env

            - name: Run Build
              run: pnpm build

            - name: Deploy Cloudflare Pages
              id: cloudflare
              uses: cloudflare/pages-action@1
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  projectName: oe-kashi
                  directory: dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}

            - name: Comment deploy url
              uses: mshick/add-pr-comment@v2
              with:
                  message-id: cloudflare-deploy
                  message: |
                      ### <span aria-hidden="true">✅</span> Deploy Preview ready!


                      |  Name | Link |
                      |---------------------------------|------------------------|
                      |<span aria-hidden="true">🔨</span> Latest commit | ${{ github.sha }} |
                      |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
                      |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.cloudflare.outputs.url }}](${{ steps.cloudflare.outputs.url }}) |
                      |<span aria-hidden="true">🌳</span> Environment | ${{ steps.cloudflare.outputs.environment }} |
                      ---

    Production:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        needs:
            - Build
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prepare
              uses: ./.github/actions/prepare

            - name: Install dependencies
              run: pnpm install

            - name: Create .env
              run: |
                  touch .env
                  echo "VITE_TEXT_ALIVE_APP_API_TOKEN=${{ secrets.TEXT_ALIVE_APP_API_TOKEN }}" >> .env

            - name: Run Build
              run: pnpm build

            - name: Deploy Cloudflare Pages
              id: cloudflare
              uses: cloudflare/pages-action@1
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  projectName: oe-kashi
                  directory: dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
